### PR TITLE
Support #disconnect and #disconnectAll

### PR DESCRIPTION
**Pull request by danilotsr**
@sanjayprabhu @dalyons @bmarini

### CODE REVIEW

**Comment by nyergler** [comment]
:+1: 

(oh hai, @dalyons!)

**Comment by adityabansod** [comment]
💥  hi guys!

**Comment by nyergler** [comment]
saltnpepa

**Comment by ejholmes** [comment]
#remindreunion2016

**Comment by adoseofjess** [comment]
:eyes: hi!

**Comment by nyergler** [comment]
Sorry, @danilotsr, no real review for you; we're having a PR Party.

**Comment by adityabansod** [comment]
would be way more fun if we were having a pool party. 🏊 
pool-party

**Comment by sdawson** [comment]
https://49.media.tumblr.com/tumblr_lpo2fcig891qbyceuo1_500.gif

**Comment by dalyons** [comment]
image

**Comment by nyergler** [comment]
HAPPY BONE SAW!! I've missed you!

**Comment by nyergler** [comment]
remind alex

**Comment by adityabansod** [comment]
@LeffelMania tagging for good measure.

**Comment by nyergler** [comment]
star-trek-fist-pump

**Comment by olgagalchenko** [comment]
The team is back together!! 💜 
fredandginger

**Comment by jmontrose** [comment]
killer robots

**Pull request merged**
